spring.application.name=finance-backend
# Server
server.port=8080

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/finance_db
spring.datasource.username=root
spring.datasource.password=pranav1910
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#  JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=finance_super_secret_jwt_key_must_be_256_bits_long_at_least_32chars
app.jwt.expiration=86400000

# Rate Limiting
app.rate-limit.requests=20
app.rate-limit.duration-minutes=1

# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

#  fix Swagger 403 issue
springdoc.swagger-ui.disable-swagger-default-url=false
spring.mvc.pathmatch.use-suffix-pattern=false
# Logging
logging.level.com.finance=DEBUG
logging.level.org.springframework.security=INFO